### ISSUE TITLE
Marketing Submission

### ISSUE THREAD

**Issue by PROTOANIC-GROUP** [PROTOANIC/F1InSchools#12]
ADDITIONAL: Marketing & Social Media document: Your 4 page / 2000 words Marketing & Social
Media document must be created on A4 or similar size, saved as a PDF file and submitted electronically to
ttillett@f1inschools.co.uk by 

**1st March**. Please refer to p39 of the Competition Regulations for score card details. 

PLEASE NOTE: file size must be no more than 10MB.

---

**Comment by PROTOANIC-GROUP** [comment]
@CameronJacobie 
What should we outline in our marketing strategy.

![image](https://user-images.githubusercontent.com/45291397/52702391-f1717580-2f73-11e9-9320-cd975d050df7.png)

How do we mention & calculate avg. 'Return on Interest' ?

**Comment by CameronJacobie** [comment]
I’d say emphasise our key beliefs so all of those slogans you already have, we also need to try and create a brand image that aligns with this same beliefs


Cameron Jacobie

On 13 Feb 2019, at 09:45, PROTOANIC GROUP <notifications@github.com<mailto:notifications@github.com>> wrote:


@CameronJacobie<https://github.com/CameronJacobie>
What should we outline in our marketing strategy.

[image]<https://user-images.githubusercontent.com/45291397/52702391-f1717580-2f73-11e9-9320-cd975d050df7.png>

How do we mention & calculate avg. 'Return on Interest' ?

**Comment by CameronJacobie** [comment]
For the interest we need to estimate how much return we “could” achieve from our car, brand etc. Then I can plot that against our spending and calculate our interest return


Cameron Jacobie

On 13 Feb 2019, at 09:45, PROTOANIC GROUP <notifications@github.com<mailto:notifications@github.com>> wrote:


@CameronJacobie<https://github.com/CameronJacobie>
What should we outline in our marketing strategy.

[image]<https://user-images.githubusercontent.com/45291397/52702391-f1717580-2f73-11e9-9320-cd975d050df7.png>

How do we mention & calculate avg. 'Return on Interest' ?

**Comment by PROTOANIC-GROUP** [comment]
Completed
