### ISSUE TITLE
Horizontal Printing of Axle

### ISSUE THREAD

**Issue by PROTOANIC-GROUP** [PROTOANIC/F1InSchools#3]
**Is your feature request related to a problem? Please describe.**
During regional final, Axle keeps breaking due to weakpoints in 3D printer. 

**Describe the solution you'd like**
Resolve this issue by acknowledging that printing in a horizontal direction will reduce 'vertical' Von-Mises Stress style issues.

**Describe alternatives you've considered**
Using different material, i.e Carbon Fibre.

**Comment by Jakobat** [comment]
This issue is irrelevant, Please close it!

**Comment by PROTOANIC-GROUP** [comment]
That's @DylanJG1 Decision, not mine.

**Comment by DylanJG1** [comment]
The front axle sheared along the beds of 3D printer filament, printing the axle horizontally would reduce the stress on these areas reducing the chance of another failure
