### ISSUE TITLE
Overweight Vehicle

### ISSUE THREAD

**Issue by PROTOANIC-GROUP** [PROTOANIC/F1InSchools#4]
**Is your feature request related to a problem? Please describe.**
Vehicle is overweight. Weighs more than 100grams. 

**Describe the solution you'd like**
Components need to be prototyped and individually weighed and recorded. Through iterative processes, reduce the weight through design and further prototyping.

**Describe alternatives you've considered**
* Lighter Solution to 'acrylic' based styling
* A reduced density 3D printing fill setting
* Innovative material solutions

**Additional context**
**P3.7 Total weight – [Critical regulation | Penalty – 6pts] **
Total weight is the weight of the car excluding a CO2 gas cartridge. If ruled underweight, ballast will be added before racing, at 0.2g for every 0.1g underweight.
**Absolute Min: 50g**

**Comment by Jakobat** [comment]
we need to make a nose cone

**Comment by James-Maxwell-02** [comment]
+ Reduce overall volume of the model. Simply make it smaller.

+ Manufacture wheels that are as narrow as possible as well as having the smallest possible diameter that still adhere to the regulations.

**Comment by DylanJG1** [comment]
smallest allowed wheel diameter is 15mm ours were ~21mm (including chamfers)

**Comment by PROTOANIC-GROUP** [comment]
Consider advantages of using a airbrush to apply colour the vehicle. Very light weight. Can be interchanged with different type of liquids.

**Comment by RoscoeG** [comment]
There is an airbrush in my room, just need to order some paint.

Most likely use tamiya acrylic based, so just let me know preference on colours etc and we can do a test piece one after school session.

**Comment by PROTOANIC-GROUP** [comment]
Colour preferences - Blackish Grey (or just black if not an option). Mild Red (#db2f08) & white.

Stencils are a good idea.

**Comment by PROTOANIC-GROUP** [comment]
Looking at design there is chance it may go underweight.
