### ISSUE TITLE
PTFE is not better than ball bearings

### ISSUE THREAD

**Issue by Jakobat** [PROTOANIC/F1InSchools#5]
**Is your feature request related to a problem? Please describe.**
~~James is arguing that Ptfe will work better than a ball bearing~~ 
James believes that PTFE will work better than a ball bearing
**Describe the solution you'd like**
Ptfe has one main issue which is that it is very hard to manufacture whilst also being heavier and very soft so it may break while racing.

**Describe alternatives you've considered**
Use ball bearings that are out of ceramic which are lighter and produces less friction furthermore make the wheel out of carbon fibre and have been milled out one CNC lathe.  This will be much easier to manufacture due to the properties of carbon fibre being strong and also it will have a lower combined weight than just ptfe.

**Additional context**
Carbon fibre's price cost less at small volume and Ptfe cost more at lower volumes so it would be better to use carbon fibre when considering cost.

**Comment by PROTOANIC-GROUP** [comment]
> Consider Ceramic prices.

**Comment by Jakobat** [comment]
yes yet again I have found an alternative, use smaller bearings which weight the same. Which have the same RPM standards.

**Comment by James-Maxwell-02** [comment]
+ The problem of PTFE being to weak, or unable to with stand the forces acting a pun it during racing can be solved by simply using PTFE spray over more solid components such as carbon-fibre. 

+ Another way to solve this problem is to just use PTFE ball bearings which would have very little friction and it also helps solve the problem of the car being overweight as the ball bearings would weigh very little.

**Comment by Jakobat** [comment]
The problem with your solution is that it requires the PTFE to be very thin and as state be for it's very soft meaning that if I drilled the first hole it would be fine however the next hole which would be very close would cause it to break or snap or warp. Furthmore a small layer of carbon fibre is also difficult unless it's done externally

**Comment by RoscoeG** [comment]
Looking at what the other professional team did, I'm not sure if they were using bearings or not - I suspect they were, but it was difficult to tell.

Another suggestion (assuming we can get bearings small enough, but more importantly light enough) is to machine the wheels from aluminium on the small metal lathe in my DT room, exactly the same as we did with the 3d printed versions, but with smaller / lighter bearings. 

A test may be needs to be done to compare the weight of 3d printed and aluminium (as small as we can get them) and assuming we are still using the bearing system, again assuming the weight is ok to use.

Just for reference, I stay after school with my GCSE students Tuesday / Wednesday and Thursday, so you are all welcome to stay as well to work on aspects of the car.
