### ISSUE TITLE
Screw mechanism to make sure the axles are secure

### ISSUE THREAD

**Issue by Jakobat** [PROTOANIC/F1InSchools#7]
Using a screw mechanism to ensure the axle stays in place would mean we would be able to exchange axles quickly if they break. however the foam used is very unversitile when it comes to threads therefore we would need to drill a hole and place in threadtube mostly likely of carbon fibre. This would not be very heavy and could help balance the car.

The problem with this is the even though it is light it still adds weight. Which could unbalance the car.

An alternative is that we could put the bearing inside the car ,this would reduce the overall weight as there is no axle system and further more the there would only be 2 move parts for each wheel which would reduce the friction. 

Additionally this may mean there is a chance of the wheel falling of as it hasn't got a lot of area to attach itself.

**Comment by DylanJG1** [comment]
Provided we don't touch the virtual cargo it shouldn't raise any issues with regulations

**Comment by PROTOANIC-GROUP** [comment]
> "The problem with this is the even though it is light it still adds weight. Which could unbalance the car."

Aerodynamical features can counteract such 'unbalance.
You would need to provide technical parameters such as weight and density so I can calculate the net aero forces that may occur on the car and negate them.

**Comment by PROTOANIC-GROUP** [comment]
This has been labelled as so because a more detailed explanation is required or a illustration is required to support this feature.
